export { default as Navigation } from "./Navigation";
export { default as Footer } from "./Footer";
export { default as Home } from "./routes/Home";
export { default as About } from "./routes/About";
export { default as Legends } from "./routes/Legends";
export { default as OneShot } from "./routes/OneShot";
export { default as Blog } from "./blog/Blog";
export { default as Posts } from "./blog/Posts";
export { default as Post } from "./blog/Post";